# Generated by Django 5.0.3 on 2024-04-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_transaction_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-time']},
        ),
        migrations.RemoveField(
            model_name='scheduledtransaction',
            name='name',
        ),
        migrations.AddField(
            model_name='scheduledtransaction',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Describe this transaction', max_length=200),
        ),
        migrations.AddField(
            model_name='scheduledtransaction',
            name='sum',
            field=models.BigIntegerField(default=0, help_text='Enter the sum of the transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='frequency',
            field=models.CharField(choices=[('w', 'Weekly'), ('m', 'Monthly'), ('y', 'Yearly'), ('d', 'Daily')], default='m', help_text='How often is the transaction occuring?', max_length=1),
        ),
    ]
