# Generated by Django 5.0.3 on 2024-04-13 10:28

import finances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='monthday',
            field=models.IntegerField(blank=True, null=True, validators=[finances.models.monthday_validator]),
        ),
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='weekday',
            field=models.IntegerField(blank=True, null=True, validators=[finances.models.weekday_validator]),
        ),
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='year_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
