# Generated by Django 5.0.3 on 2024-04-14 10:54

import finances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_alter_scheduledtransaction_monthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True, validators=[finances.models.weekday_validator]),
        ),
    ]
